# Generated by Django 4.1.2 on 2022-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="ip_phone",
            field=models.CharField(default="tet", max_length=20),
            preserve_default=False,
        ),
    ]
